repos:
- repo: local
  hooks:
  - id: lint-code
    name: lint-code
    entry: ruff check --fix
    language: system
    always_run: true
    pass_filenames: false
  - id: format-code
    name: format-code
    entry: ruff format
    language: system
    always_run: true
    pass_filenames: false
  - id: check-types
    name: check-types
    entry: ty check
    language: system
    always_run: true
    pass_filenames: false
  - id: check-security
    name: check-security
    entry: bandit -c pyproject.toml -r .
    language: system
    always_run: true
    pass_filenames: false
  - id: check-markdown
    name: check-markdown
    entry: rumdl check
    language: system
    always_run: true
    pass_filenames: false
