name: Publish
'on':
  workflow_dispatch: {}
  workflow_run:
    workflows:
    - Release
    types:
    - completed
permissions: {}
run-name: Publish
defaults:
  run:
    shell: bash
env:
  PYTHONDONTWRITEBYTECODE: 1
  UV_NO_SYNC: 1
jobs:
  publish_package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: Setup Git
      id: setup_git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Package Manager
      id: setup_package_manager
      uses: astral-sh/setup-uv@main
      with:
        python-version: '3.14'
    - name: Build Wheel
      id: build_wheel
      run: uv build
    - name: Publish To Pypi
      id: publish_to_pypi
      run: 'if [ ${{ secrets.PYPI_TOKEN }} ]; then uv publish --token ${{ secrets.PYPI_TOKEN
        }}; else echo "Skipping step due to failed condition: secrets.PYPI_TOKEN.";
        fi'
  publish_documentation:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: Setup Git
      id: setup_git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Package Manager
      id: setup_package_manager
      uses: astral-sh/setup-uv@main
      with:
        python-version: '3.14'
    - name: Update Dependencies
      id: update_dependencies
      run: uv lock --upgrade
    - name: Install Dependencies
      id: install_dependencies
      run: uv sync
    - name: Build Documentation
      id: build_documentation
      run: uv run mkdocs build
    - name: Enable Pages
      id: enable_pages
      uses: actions/configure-pages@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
        enablement: 'true'
    - name: Upload Documentation
      id: upload_documentation
      uses: actions/upload-pages-artifact@main
      with:
        path: site
    - name: Publish Documentation
      id: publish_documentation
      uses: actions/deploy-pages@main
